export const EMAIL_CHANGE = "EMAIL_CHANGE";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const LOGIN_SENT = "LOGIN_SENT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REJECTED = "LOGIN_REJECTED";
export const CREATE_ACCOUNT="CREATE_ACCOUNT";
export const ACCOUNT_NOT_CREATED="ACCOUNT_NOT_CREATED";
